(defun tmp ()
  (interactive)
  (find-file "~/tmp/tmp"))
(defun gtd ()
  (interactive)
  (find-file "~/org_data/gtd.org"))
(defun in-basket ()
  (interactive)
  (find-file "~/org_data/in-basket.org"))
(defun skill ()
  (interactive)
  (find-file "~/org_data/pkm/pkm-skill.org"))
(defun projects ()
  (interactive)
  (find-file "~/org_data/projects.org"))
(defun someday ()
  (interactive)
  (find-file "~/org_data/someday.org"))
(defun pkm ()
  (interactive)
  (find-file "~/org_data/pkm/pkm.org"))
(defun work ()
  (interactive)
  (find-file "~/org_data/pkm/pkm-work.org"))
(defun password ()
  (interactive)
  (find-file "~/org_data/passwords.org.gpg"))

;;(defun career ()
;;  (interactive)
;;  (find-file "~/org_data/career.org"))
;;(defun work ()
;;  (interactive)
;;  (find-file "~/org_data/work.org"))
;;(defun often ()
;;  (interactive)
;;  (find-file "~/org_data/often.org"))
;;(defun mydiary ()
;;  (interactive)
;;  (find-file "~/org_data/diary.org"))
;;(defun top ()
;;  (interactive)
;;  (find-file "~/org_data/top.org"))
;;(defun password ()
;;  (interactive)
;;  (find-file "~/org_data/password.org.gpg"))
;;(defun programming ()
;;  (interactive)
;;  (find-file "~/org_data/programming.org"))
;;(defun communication ()
;;  (interactive)
;;  (find-file "~/org_data/communication.org"))
;;(defun contact ()
;;  (interactive)
;;  (find-file "~/org_data/contacts.org"))
;;(defun motto ()
;;  (interactive)
;;  (find-file "~/emacs_conf/signature-motto.el"))
;;
;;

